POST http://kiwibot-challenge-25486.firebaseapp.com/api/bots
Content-Type: application/json

{
  "id": "uuidv4()",
  "status": "botsBody.status",
  "location": {
    "dropoffLat": "botsBody.dropoffLat",
    "dropoffLon": "botsBody.dropoffLon"
  },
  "zoneId": "botsBody.zoneId"
}