POST https://kiwibot-challenge-25486-default-rtdb.firebaseio.com/api/delivery_orders.json
Content-Type: application/json

{
  "id": "uuidv4()",
  "creationDate": "new Date().toISOString()",
  "status": "",
  "pickup": {
    "pickupLat": 0,
    "pickupLon": 0
  },
  "dropoff": {
    "dropoffLat": 0,
    "dropoffLon": 0
  },
  "zoneId": ""
}