POST https://kiwibot-challenge-25486-default-rtdb.firebaseio.com/api/bots.json
Content-Type: application/json

{
  "id": "uuidv4()",
  "status": "botsBody.status",
  "location": {
    "dropoffLat": "botsBody.dropoffLat",
    "dropoffLon": "botsBody.dropoffLon"
  },
  "zoneId": "botsBody.zoneId"
}